# Generated by Django 3.1.1 on 2021-03-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('isbn13', models.CharField(max_length=20)),
                ('isbn', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=200)),
                ('product_id', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=200)),
                ('customer_rating', models.FloatField()),
            ],
        ),
    ]
