# Generated by Django 3.1.1 on 2021-03-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210309_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='customer_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='isbn13',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
